//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BillysRentals2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Item()
        {
            this.OrderItemDetails = new HashSet<OrderItemDetail>();
            this.OrderItems = new HashSet<OrderItem>();
            this.ItemTypes = new HashSet<ItemType>();
        }
    
        public int ItemID { get; set; }
        public Nullable<int> MasterItemID { get; set; }
        public string ItemName { get; set; }
        public Nullable<int> Category { get; set; }
        public string ItemDescription { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<decimal> PriceEach { get; set; }
        public Nullable<int> MaintenanceIntervalDays { get; set; }
        public string Model { get; set; }
        public string Manufacturer { get; set; }
        public Nullable<System.DateTime> DateAcquired { get; set; }
        public Nullable<System.DateTime> DateInService { get; set; }
        public Nullable<System.DateTime> DateDisposed { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public string ItemPicturePath { get; set; }
    
        public virtual Category Category1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderItemDetail> OrderItemDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderItem> OrderItems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ItemType> ItemTypes { get; set; }
    }
}
