//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BillysRentals2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderItem
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OrderItem()
        {
            this.OrderItemDetails = new HashSet<OrderItemDetail>();
        }
    
        public int ID { get; set; }
        public int OrderID { get; set; }
        public int ItemID { get; set; }
        public int ItemTimePeriodID { get; set; }
        public int Quantity { get; set; }
        public Nullable<decimal> Price { get; set; }
        public int Duration { get; set; }
        public Nullable<int> DiscountID { get; set; }
        public Nullable<decimal> DiscountAmount { get; set; }
        public string ItemComment { get; set; }
        public System.DateTime DateModified { get; set; }
        public byte[] UpdateTimeStamp { get; set; }
        public System.DateTime DateEntered { get; set; }
        public decimal OverRidePrice { get; set; }
        public Nullable<decimal> SalesTaxRateUsed { get; set; }
        public Nullable<int> DepositRefundOrderID { get; set; }
    
        public virtual Item Item { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderItemDetail> OrderItemDetails { get; set; }
        public virtual Order Order { get; set; }
        public virtual Order Order1 { get; set; }
    }
}
