//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BillysRentals2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderNote
    {
        public int ID { get; set; }
        public int OrderID { get; set; }
        public string Note { get; set; }
        public System.DateTime DateModified { get; set; }
        public byte[] UpdateTimeStamp { get; set; }
        public int NoteEnteredBy { get; set; }
    
        public virtual Order Order { get; set; }
    }
}
