//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BillysRentals2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.OrderItems = new HashSet<OrderItem>();
            this.OrderItems1 = new HashSet<OrderItem>();
            this.OrderNotes = new HashSet<OrderNote>();
        }
    
        public int ID { get; set; }
        public int EnteredByUserID { get; set; }
        public int OrderStatusID { get; set; }
        public Nullable<decimal> DiscountAmount { get; set; }
        public Nullable<decimal> DepositAmount { get; set; }
        public bool IsDepositRefundable { get; set; }
        public Nullable<int> PersonCount { get; set; }
        public Nullable<int> OrderItemsCount { get; set; }
        public System.DateTime DateModified { get; set; }
        public byte[] UpdateTimeStamp { get; set; }
        public Nullable<int> DefaultReturnMethodID { get; set; }
        public Nullable<int> CompanyUsedID { get; set; }
        public Nullable<int> RentalCompanyID { get; set; }
        public string FolioNumber { get; set; }
        public Nullable<decimal> DiscountPercentage { get; set; }
        public Nullable<int> DefaultTimePeriodID { get; set; }
        public System.DateTime OrderDate { get; set; }
        public Nullable<decimal> SalesTaxRate { get; set; }
        public Nullable<int> OrderSourceID { get; set; }
        public Nullable<System.DateTime> OrderClosedDate { get; set; }
        public Nullable<System.DateTime> VoidDate { get; set; }
        public Nullable<decimal> RentalCompanyCommRate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderItem> OrderItems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderItem> OrderItems1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderNote> OrderNotes { get; set; }
        public virtual OrderSource OrderSource { get; set; }
    }
}
